---
- hosts: app
  vars:
    docker_registry: nexus3.inspq.qc.ca:5000
    sx5javarestoidc_internal_port: "{{ sx5javarestoidc_external_port }}"
    sx5javarestoidc_docker_image: "{{ docker_registry }}/inspq/sx5javarestoidc"
    
  roles:
  - docker-engine
      
  tasks:

  - name: Docker repository logon
    shell: docker login -u {{ docker_registry_username }} -p  {{ docker_registry_password }} -e {{ docker_registry_email }} {{ docker_registry }}
    when: docker_registry_username is defined and docker_registry_password is defined and docker_registry_email is defined

  - name: Suppression du conteneur pour sx5javarestoidc 
    docker:
      name: "{{ sx5javarestoidc_container_name }}"
      image: "{{ sx5javarestoidc_docker_image }}:{{ sx5javarestoidc_image_version }}"
      state: absent
    
  - name: Mettre a jour l'image Docker
    docker_image: 
      name: "{{ sx5javarestoidc_docker_image }}"
      tag: "{{ sx5javarestoidc_image_version }}"
      pull: true
      state: present
      force: yes
      
  - name: Creation du conteneur pour sx5javarestoidc 
    docker_container:
      name: "{{ sx5javarestoidc_container_name }}"
      image: "{{ sx5javarestoidc_docker_image }}:{{ sx5javarestoidc_image_version }}"
      state: started
      restart_policy: unless-stopped
      ports:
      - "{{ sx5javarestoidc_external_port }}:{{ sx5javarestoidc_internal_port }}"
      env:
        "OPENAM_URL": "{{openam_url}}"
        "OIDC_CLIENT_ID": "{{sx5javarestoidc_oidc_client_id}}"
        "OIDC_CLIENT_SECRET": "{{sx5javarestoidc_oidc_client_secret}}"
        "OIDC_REDIRECT_URI": "{{sx5javarestoidc_oidc_redirect_uri}}"
        "CATALINA_OPTS": "-Djava.security.egd=file:/dev/./urandom -Dsecurity.jwt.jwks_uri={{ jwks_uri }} -DOPENAM_URL={{openam_url}} -DOIDC_CLIENT_ID={{sx5javarestoidc_oidc_client_id}} -DOIDC_CLIENT_SECRET={{sx5javarestoidc_oidc_client_secret}} -DOIDC_REDIRECT_URI={{sx5javarestoidc_oidc_redirect_uri}} -DSERVER_PORT={{sx5javarestoidc_internal_port}}"

  - name: Verifier si le firewall est actif
    command: systemctl status firewalld
    ignore_errors: yes
    register: security_firewall
     
  - name: Ouvrir le port {{ sx5javarestoidc_external_port }}
    firewalld: port="{{ sx5javarestoidc_external_port }}/tcp" state=enabled immediate=true permanent=true
    when: ansible_distribution_major_version == "7" and ansible_os_family == "RedHat" and security_firewall is defined and security_firewall.rc == 0
          
  - name: Creation du hote virtuel dans APACHE
    template:
      src: sx5javarestoidc-gabarit-apache.conf
      dest: /etc/httpd/conf.d/{{ sx5javarestoidc_base_url }}.conf
      force: yes
    when: sx5javarestoidc_base_url is defined
    notify:
      - restart httpd  
      
  handlers:
  - name: restart httpd 
    service: name=httpd state=restarted
