---
- hosts: app
  vars:
    docker_registry: nexus3.inspq.qc.ca:5000
    sx5javaui_internal_port: 8080
    sx5javaui_docker_image: "{{ docker_registry }}/inspq/sx5javaui"
    
  roles:
  - docker-engine
      
  tasks:

  - name: Docker repository logon
    shell: docker login -u {{ docker_registry_username }} -p  {{ docker_registry_password }} -e {{ docker_registry_email }} {{ docker_registry }}
    when: docker_registry_username is defined and docker_registry_password is defined and docker_registry_email is defined

  - name: Suppression du conteneur pour sx5javaui 
    docker:
      name: "{{ sx5javaui_container_name }}"
      image: "{{ sx5javaui_docker_image }}:{{ sx5javaui_image_version }}"
      state: absent
    
  - name: Mettre a jour l'image Docker
    docker_image: 
      name: "{{ sx5javaui_docker_image }}"
      tag: "{{ sx5javaui_image_version }}"
      pull: true
      state: present
      force: yes
      
  - name: Creation du conteneur pour sx5javaui 
    docker_container:
      name: "{{ sx5javaui_container_name }}"
      image: "{{ sx5javaui_docker_image }}:{{ sx5javaui_image_version }}"
      state: started
      restart_policy: unless-stopped
      ports:
      - "{{ sx5javaui_external_port }}:{{ sx5javaui_internal_port }}"
      env:
        "JAVA_REST_BASE_URL": "http://{{ sx5javarest_base_url }}:{{ sx5javarest_external_port }}"
        "JAVA_SOAP_BASE_URL": "http://{{ sx5javarest_base_url }}:{{ sx5javarest_external_port }}"
        "DOTNET_REST_BASE_URL": "http://{{ sx5dotnetrest_base_url }}:{{ sx5dotnetrest_external_port }}"
        "AGENT_PWD": "{{sx5javaui_agent_pwd}}"
        "OPENAM_URL": "{{openam_url}}"
        "AGENT_URL": "{{sx5javaui_agent_url}}"
        "AGENT_PROFILE_NAME": "{{sx5javaui_agent_profile_name}}"      
        
  - name: Creation du hote virtuel dans APACHE
    template:
      src: sx5javaui-gabarit-apache.conf
      dest: /etc/httpd/conf.d/{{ sx5javaui_base_url }}.conf
      force: yes
    when: sx5javaui_base_url is defined
    notify:
      - restart httpd  
      
  handlers:
  - name: restart httpd 
    service: name=httpd state=restarted
